assign/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('show/',include('show.urls')),
    path('admin/', admin.site.urls),
]

if not settings.DEBUG:
    urlpatterns += [url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})]

show/urls.py
from django.urls import path

from . import views

app_name = 'show'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/',views.adduser,name='adduser'),
    path('ex/<user_id>',views.experiment,name='exper'),
    path('addex/',views.addexper,name='addex'),
    path('finish/',views.finish,name='finish'),
    path('exists/',views.existsuser,name='exists'),
    path('modify/',views.modifyGL,name='modify')
]

show/models.py
from django.db import models

# Create your models here.
class Choice(models.Model):
    choice_id = models.AutoField(verbose_name="选择id",primary_key=True)
    choice_user_id = models.CharField(max_length=100,verbose_name="用户编号")
    choice_times = models.IntegerField(verbose_name="当前实验次数")
    choice_area = models.FloatField(verbose_name="种植水稻的土地面积")
    choice_saving = models.FloatField(verbose_name="储蓄金额")
    choice_insurance = models.FloatField(verbose_name="保险金额")
    choice_lost_situation = models.CharField(max_length=20,verbose_name="受灾赔偿情况")
    choice_affected_degree = models.FloatField(verbose_name="受灾程度",null=True,blank=True)
    choice_gain_money = models.FloatField(verbose_name="获得赔偿金额",null=True,blank=True)
    choice_affected_date = models.IntegerField(verbose_name="受灾日期",null=True,blank=True)
    choice_before_affected_saving_sum = models.FloatField(verbose_name="受灾前储蓄本息和",null=True,blank=True)
    choice_current_remain = models.FloatField(verbose_name="受灾时账户余额",null=True,blank=True)
    choice_is_get = models.CharField(max_length=10,verbose_name="是否从账户中取出钱")
    choice_reduce_money = models.FloatField(verbose_name="取出金额")
    choice_after_affected = models.FloatField(verbose_name="受灾后至产品周期结束账户内金额的本息和",null=True,blank=True)
    choice_balance = models.FloatField(verbose_name="本次账户余额（元/亩）")
    choice_total_balance = models.FloatField(verbose_name="账户总余额")
    class Meta:
        verbose_name="实验记录"
        verbose_name_plural="实验记录"

class UserChoice(models.Model):
    uc_id = models.AutoField(verbose_name="id",primary_key=True)
    uc_user_id = models.CharField(max_length=100,verbose_name="用户编号")
    uc_total_money = models.FloatField(verbose_name="愿意投入金额")
    uc_total_saving = models.FloatField(verbose_name="储蓄愿意投入金额")
    uc_total_insurance = models.FloatField(verbose_name="保险愿意投入金额")
    uc_final_choice = models.CharField(max_length=100,verbose_name="用户最终选择",blank=True,null=True)
    uc_integral = models.FloatField(verbose_name="最终积分",blank=True,null=True)
    class Meta:
        verbose_name="所有用户"
        verbose_name_plural="所有用户"

show/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.urls import reverse
from show.models import Choice,UserChoice
import random

# Create your views here.
def index(request):
    context = {}
    return render(request,'index.html',context)
def modifyGL(request):
    context = {}
    return render(request,'modify.html',context)
def finish(request):
    context = {}
    context['data'] = []
    db = UserChoice.objects.all()
    for user in db:
        user_id = user.uc_user_id
        total_money = user.uc_total_money
        total_saving = user.uc_total_saving
        total_insurance = user.uc_total_insurance
        final_choice = user.uc_final_choice
        integral = user.uc_integral
        obj = Choice.objects.filter(choice_user_id=user_id)
        times = len(obj)
        temp = {
            'user_id':user_id,
            'times':times,
            'total_money':total_money,
            'total_saving':total_saving,
            'total_insurance':total_insurance,
            'final_choice':final_choice,
            'integral':integral
        }
        context['data'].append(temp)
    return render(request,'finish.html',context)
def existsuser(request):
    if request.method == "POST":
        user_id = str(request.POST['user_id'])
        res = {}
        res['user_id'] = user_id
        res['check'] = 0
        try:
            q = UserChoice.objects.get(uc_user_id=user_id)
            res['check'] = 1
        except UserChoice.DoesNotExist:
            res['check'] = 0
        return JsonResponse(res)
def adduser(request):
    if request.method == "POST":
        user_id = str(request.POST['user_id'])
        total_money = float(request.POST['total_money'])
        total_saving = float(request.POST['total_saving'])
        total_insurance = float(request.POST['total_insurance'])
        try:
            q = UserChoice.objects.get(uc_user_id=user_id)
            q.uc_total_money = total_money
            q.uc_total_saving = total_saving
            q.uc_total_insurance = total_insurance
            q.save()
        except UserChoice.DoesNotExist:
            db = UserChoice(uc_user_id=user_id,uc_total_money=total_money,uc_total_saving=total_saving,uc_total_insurance=total_insurance)
            db.save()
        resdata = {}
        resdata['url'] = "/show/ex/" + user_id
        return JsonResponse(resdata)

def experiment(request,user_id):
    context = {
        "tag":0,
        "user_id":user_id,
        "times":1,
        "t_area":0.0,
        "last_remain":0.00,
        "last_choice":"",
        "ex_introduce":"接下来您将有八次机会分配该账户中的钱，每次分配的金额为20（元/亩）。您有一定的概率遭受灾害，请根据每次账户余额，调整下一次分配比重。",
        "data":[]
    }
    try:
        db = Choice.objects.all().filter(choice_user_id=user_id)
        context['tag'] = 1
        context['times'] = len(db) + 1
        for item in db:
            temp = {}
            temp['user_id'] = item.choice_user_id
            temp['ex_times'] = item.choice_times
            temp['area'] = item.choice_area
            context['t_area'] = temp['area']
            temp['saving'] = item.choice_saving
            temp['insurance'] = item.choice_insurance
            temp['lost_situation'] = item.choice_lost_situation
            temp['gain_money'] = item.choice_gain_money
            temp['current_remain'] = item.choice_current_remain
            temp['reduce_money'] = item.choice_reduce_money
            temp['balance'] = item.choice_balance
            context['last_remain'] = temp['balance']
            temp['total_balance'] = item.choice_total_balance
            context['data'].append(temp)
    except Choice.DoesNotExist:
        context['tag'] = 0
    if context['times'] == 9:
        try:
            uc = UserChoice.objects.get(uc_user_id=user_id)
            if uc.uc_final_choice:
                context['last_choice'] = uc.uc_final_choice
                context['times'] += 1
        except UserChoice.DoesNotExist:
            context['last_choice'] = ""
    return render(request,'experiment.html',context)

def addexper(request):
    money_intitial = 20 #初始投入金额(元)
    saving_profits = 1.35 #储蓄利润(%)
    saving_year_profits = 1.75
    product_cycle = 3 #产品周期(月)
    premium_rate = 7.0 #保险费率(%)
    current_savings_rate = 0.55/100.0 #活期储蓄利率

    saving_profits /= 100.0
    saving_year_profits /= 100.0
    product_cycle /= 12.0
    premium_rate /= 100.0

    user_id = str(request.POST['user_id'])
    ex_times = int(request.POST['ex_times'])
    if ex_times <= 8:
        last_remain = float(request.POST['last_remain']) #账户余额
        area = float(request.POST['area']) #亩
        saving = float(request.POST['saving']) #储蓄金额
        insurance = float(request.POST['insurance']) #保险金额
        lost_situation = request.POST['lost_situation']
        affected_degree = float(request.POST['affected_degree']) #受灾程度0-0.7
        gain_money = float(request.POST['gain_money']) #赔偿金额
        affected_date = int(request.POST['affected_date']) #受灾日期
        before_affected_saving_sum = float(request.POST['before_affected_saving_sum'])
        current_remain = float(request.POST['current_remain'])
        is_get = request.POST['is_get'] #是否取出钱
        reduce_money = 0.00 #取出金额
        if is_get == "1":
            is_get = "是"
            reduce_money = float(request.POST['reduce_money'])
        else:
            is_get = "否"
        # 受灾后至产品周期结束账户内金额的本息和
        after_affected_sum = (current_remain-reduce_money)*(1+current_savings_rate*(90-affected_date)*(1/365.0))
        balance = after_affected_sum*(1+1.65/100.0*(9/12)) #账户余额
        total_balance = balance * area #账户总余额

        area = round(area,1)
        # 保留两位小数
        saving = round(saving,2)
        insurance = round(insurance,2)
        affected_degree = round(affected_degree,2)
        gain_money = round(gain_money,2)
        before_affected_saving_sum = round(before_affected_saving_sum,2)
        current_remain = round(current_remain,2)
        reduce_money = round(reduce_money,2)
        after_affected_sum = round(after_affected_sum,2)
        balance = round(balance,2)
        total_balance = round(total_balance,2)
        db = Choice(
            choice_user_id=user_id,
            choice_times=ex_times,
            choice_area=area,
            choice_saving=saving,
            choice_insurance=insurance,
            choice_lost_situation=lost_situation,
            choice_affected_degree=affected_degree,
            choice_gain_money=gain_money,
            choice_affected_date=affected_date,
            choice_before_affected_saving_sum=before_affected_saving_sum,
            choice_current_remain=current_remain,
            choice_is_get=is_get,
            choice_reduce_money=reduce_money,
            choice_after_affected=after_affected_sum,
            choice_balance=balance,
            choice_total_balance=total_balance
        )
        db.save()
    else:
        final_choice = str(request.POST['final_choice'])
        integral = int(request.POST['integral'])
        uc = UserChoice.objects.get(uc_user_id=user_id)
        uc.uc_final_choice = final_choice
        uc.uc_integral = integral
        uc.save()
    return HttpResponseRedirect(reverse('show:exper',kwargs={'user_id':user_id}))

show/templates/experiment.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <!-- bootstrap.bundle.min.js 用于弹窗、提示、下拉菜单，包含了 popper.min.js -->
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <title>用户实验</title>
</head>
<body>
    <div class="container" style="margin-top: 20px;margin-bottom: 20px;">
        <div class="card">
            <div class="card-header bg-info text-center text-white">
                <h1>当前是编号为<span class="text-primary">{{user_id}}</span>的实验者</h1>
            </div>
            <div class="card-body">
                <h3 class="text-warning">{{ex_introduce}}</h3>
                {% if times > 8 %}
                    <h3>实验结束！感谢参与！</h3>
                {% else %}
                    <h3>当前实验次数：{{times}}</h3>
                {% endif %}
                <form role="form" id="myform" action="{% url 'show:addex' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value="{{user_id}}">
                    <input type="hidden" name="ex_times" id="ex_times" value="{{times}}">
                    <input type="hidden" name="last_remain" id="last_remain" value="{{last_remain}}">
                    <input type="hidden" name="affected_degree" id="affected_degree" value="0.0"/>
                    <input type="hidden" name="affected_date" id="affected_date" value="0">
                    <input type="hidden" name="gain_money" id="gain_money" value="0.00">
                    <input type="hidden" name="before_affected_saving_sum" id="before_affected_saving_sum" value="0.00">
                    {% if times <= 8 %}
                    <div class="form-group">
                        <label for="area">您拥有的水稻种植面积为？（亩）</label>
                        <input type="number" name="area" class="form-control" id="area" min="0.0" max="10000000.0" step="0.1" value="{{t_area}}">
                    </div>
                    <div class="form-group">
                        <label for="saving">储蓄金额（元/亩）【储蓄金额+保险金额=20.0（元/亩）】</label>
                        <input type="number" name="saving" id="saving" class="form-control" min="0.00" max="20.00" step="0.01">
                    </div>
                    <div class="form-group">
                        <label for="insurance">保险费（元/亩）</label>
                        <input type="number" name="insurance" class="form-control" id="insurance" readonly>
                    </div>
                    <div class="form-group">
                        <label for="lost_situation">受灾赔偿情况</label>
                        <input type="text" name="lost_situation" class="form-control" id="lost_situation" readonly>
                    </div>
                    <div class="form-group">
                        <label for="lost_money">受损金额</label>
                        <input type="text" name="lost_money" class="form-control" id="lost_money" readonly>
                    </div>
                    <div id="lost_show_1" style="display: block;">
                        <p style="color: red;">赔偿后可选，不赔偿默认为“否”</p>
                    </div>
                    <div class="form-group" id="lost_show_2" style="display: block;">
                        <label for="is_get">是否从账户中取钱？</label>
                        <select name="is_get" id="is_get">
                            <option value="1">是</option>
                            <option value="2" selected="selected">否</option>
                        </select>
                    </div>
                    <div class="form-group" id="cur_show" style="display: none;">
                        <label for="current_remain">受灾时账户余额（元/亩）</label>
                        <input type="number" readonly name="current_remain" id="current_remain" value="0.00">
                    </div>
                    <div class="form-group" id="lost_show_3" style="display: block;">
                        <label for="reduce_money">取出金额为（元/亩）</label>
                        <input type="number" name="reduce_money" min="0.00" max="1000000000.00" step="0.01" value="">
                    </div>
                    {% elif times == 9 %}
                    <div class="form-group">
                        <label for="integral">您本次实验获得的积分为</label>
                        <input type="number" class="form-control" name="integral" id="integral" readonly value="0">
                    </div>
                    <div class="form-group">
                        <label for="final_choice">恭喜您完成实验，请填写您最满意的储蓄保险分配比重？</label>
                        <input type="text" class="form-control" name="final_choice">
                    </div>
                    {% endif %}
                    {% if times <= 9 %}
                    <div class="text-center">
                        <input class="btn btn-success" style="margin-top:10px;margin-bottom:10px;width: 100%;" type="submit" value="提交">
                    </div>
                    {% endif %}
                </form>
                {% if times > 9 %}
                <h4>您最满意的储蓄保险分配比重为：{{last_choice}}</h4>
                <p><a href="{% url 'show:index' %}">下一位用户</a></p>
                {% endif %}
                <div class="table-responsive">
                    <table class="table table-bordered text-center">
                        <thead>
                            <tr>
                                <th>选择</th>
                                <th>储蓄金额</th>
                                <th>保险金额</th>
                                <th>受灾赔偿情况</th>
                                <th>获得赔偿金额</th>
                                <th>受灾时账户余额</th>
                                <th>是否从账户取钱</th>
                                <th>取出金额</th>
                                <th>本次账户余额（元/亩）</th>
                                <th>账户总余额</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if tag == 1 %}
                                {% for item in data %}
                                    <tr>
                                        <td>{{item.ex_times}}</td>
                                        <td>{{item.saving}}</td>
                                        <td>{{item.insurance}}</td>
                                        <td>{{item.lost_situation}}</td>
                                        <td>{{item.gain_money}}</td>
                                        <td>{{item.current_remain}}</td>
                                        {% if item.reduce_money > 0.00 %}
                                        <td>是</td>
                                        {% else %}
                                        <td>否</td>
                                        {% endif %}
                                        <td>{{item.reduce_money}}</td>
                                        <td>{{item.balance}}</td>
                                        <td>{{item.total_balance}}</td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        var ex_times = document.getElementById('ex_times');

        var saving = document.getElementById('saving');
        var insurance = document.getElementById('insurance');
        var last_remain = document.getElementById('last_remain');

        if (parseInt(ex_times.value) == 9){
            var integral = document.getElementById('integral');
            integral.value = parseFloat(last_remain.value);
            if (integral.value <= 130)
                integral.value = 5;
            else if (integral.value < 700)
                integral.value = 10;
            else
                integral.value = 15;
        }

        var current_remain = document.getElementById('current_remain');

        var lost_situation = document.getElementById('lost_situation');
        var lost_money = document.getElementById('lost_money');
        var affected_degree = document.getElementById('affected_degree');
        var affected_date = document.getElementById('affected_date');
        var before_affected_saving_sum = document.getElementById('before_affected_saving_sum');
        var gain_money = document.getElementById('gain_money');

        var lost_show_1 = document.getElementById('lost_show_1');
        var lost_show_2 = document.getElementById('lost_show_2');
        var lost_show_3 = document.getElementById('lost_show_3');

        var cur_show = document.getElementById('cur_show');

        var is_get = document.getElementById('is_get');

        saving.oninput = function(){
            if (saving.value == ''){
                insurance.value = '';
                lost_situation.value = '';
            }else{
                if (saving.value > 20){
                    alert("输入的储蓄金额值大于20！");
                    saving.value = '';
                    insurance.value = '';
                    lost_situation.value = '';
                    return;
                }
                insurance.value = 20 - saving.value;
                var random_seed = parseInt(Math.random()*100000,10);
                var lost_money_random = parseFloat(random_seed) / 100000.0 * 285;
                var type = '';
                if (random_seed <= 19025)
                    type = 'A';
                else if (random_seed <= 22000)
                    type = 'B';
                else if (random_seed <= 22316)
                    type = 'C';
                else
                    type = 'D';
                lost_money.value = 0;
                switch(type){
                    case 'A':
                       lost_situation.value = "A.受灾赔偿";
                       lost_money.value = lost_money_random;
                       break;
                    case 'B':
                        lost_situation.value = 'B.受灾没赔偿';
                        lost_money.value = lost_money_random;
                        break;
                    case 'C':
                        lost_situation.value = 'C.没受灾赔偿';
                        break;
                    case 'D':
                        lost_situation.value = 'D.没受灾没赔偿';
                        break;
                    default:
                        lost_situation.value = '';
                        lost_money.value = 0;
                }
                affected_degree.value = Math.round(Math.random()*0.7*100)/100;
                affected_date.value = parseInt(Math.random()*91,10);
                
                before_affected_saving_sum.value = (parseFloat(saving.value) + parseFloat(last_remain.value))*(1+0.0055*affected_date.value*(1/365));
                before_affected_saving_sum.value = Math.round(before_affected_saving_sum.value*100)/100;
                
                if (type == 'B' || type == 'D'){
                    lost_show_1.style.display = "none";
                    lost_show_2.style.display = "none";
                    lost_show_3.style.display = "none";
                    gain_money.value = 0;
                    is_get.value = "2";
                }
                if (type == 'A' || type == 'C'){
                    lost_show_1.style.display = "block";
                    lost_show_2.style.display = "block";
                    lost_show_3.style.display = "block";
                    gain_money.value = (parseFloat(insurance.value)/0.07)*affected_degree.value;
                    is_get.onchange = function(){
                        var cur = is_get.value;
                        if (cur == '1'){
                            cur_show.style.display = "block";
                        }else{
                            cur_show.style.display = "none";
                        }
                    }
                }
                current_remain.value = parseFloat(gain_money.value) + parseFloat(before_affected_saving_sum.value);

                gain_money.value = Math.round(gain_money.value*100)/100;
                current_remain.value = Math.round(current_remain.value*100)/100;
            }
        }
    </script>
</body>
</html>

show/templates/finish.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <!-- bootstrap.bundle.min.js 用于弹窗、提示、下拉菜单，包含了 popper.min.js -->
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <title>已经实验用户</title>
</head>
<body>
    <div class="container" style="margin-top: 20px;">
        <h3 class="text-center" style="margin-bottom: 20px;">已经实验用户</h3>
        <div class="table-responsive">
            <table class="table table-bordered text-center">
                <thead>
                    <tr>
                        <th>选择</th>
                        <th>用户编号</th>
                        <th>已经实验次数</th>
                        <th>愿意投入总金额</th>
                        <th>储蓄投入金额</th>
                        <th>保险投入金额</th>
                        <th>最终积分</th>
                        <th>最满意的比重</th>
                        <th>完成状态</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="table-responsive" style="overflow: scroll;max-height: 500px;">
            <table class="table table-bordered text-center">
                <thead>
                    <tr>
                        <th>选择</th>
                        <th>用户编号</th>
                        <th>已经实验次数</th>
                        <th>愿意投入总金额</th>
                        <th>储蓄投入金额</th>
                        <th>保险投入金额</th>
                        <th>最终积分</th>
                        <th>最满意的比重</th>
                        <th>完成状态</th>
                    </tr>
                </thead>
                <tbody id="get_select">
                    {% for item in data %}
                    <tr>
                        <td><input type="radio" name="select_r"></td>
                        <td>{{item.user_id}}</td>
                        <td>{{item.times}}</td>
                        <td>{{item.total_money}}</td>
                        <td>{{item.total_saving}}</td>
                        <td>{{item.total_insurance}}</td>
                        <td>{{item.integral}}</td>
                        {% if item.final_choice %}
                        <td>{{item.final_choice}}</td>
                        {% else %}
                        <td>未选择</td>
                        {% endif %}
                        {% if item.times == 8 %}
                        <td>已完成</td>
                        {% else %}
                        <td>未完成</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row text-center" style="margin-top: 20px;margin-bottom: 50px;">
            <div class="col">
                <button id="comeon" class="btn btn-success" style="width: 60%;">继续完成实验</button>
            </div>
        </div>
    </div>
    <script>
        $('#comeon').click(function(){
            var getSelect = document.getElementById('get_select');
            var alltr = getSelect.getElementsByTagName('tr');
            for(var i = 0; i < alltr.length; i++){
                var childNodes = alltr[i].childNodes;
                var check = childNodes[1].childNodes[0].checked;
                if (check){
                    var times = childNodes[5].childNodes[0].data;
                    if (times == 8){
                        alert("该用户已经做完实验^_^");
                        return;
                    }
                    var user = childNodes[3].childNodes[0].data;
                    location.href = "/show/ex/" + user;
                }
            }
        });
    </script>
</body>
</html>

show/templates/modify.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <!-- bootstrap.bundle.min.js 用于弹窗、提示、下拉菜单，包含了 popper.min.js -->
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <title>修改概率</title>
</head>
<body>
    <div class="container" style="margin-top: 20px;margin-bottom: 20px;">
        <div class="card">
            <div class="card-header text-center bg-info text-white">
                <h1>修改概率</h1>
            </div>
            <div class="card-body">
                <h4 class="text-info">描述</h4>
                <p>
                    每一类的概率
                </p>
                <form role="form">
                    <div class="form-group">
                        <label for="gl_A">A. 受灾赔偿</label>
                        <input id="gl_A" type="text" class="form-control" value="">
                    </div>
                    <div class="form-group">
                        <label for="gl_B">B. 受灾没赔偿</label>
                        <input id="gl_B" type="number" class="form-control" value="">
                    </div>
                    <div class="form-group">
                        <label for="gl_C">C. 没受灾赔偿</label>
                        <input id="gl_C" type="number" class="form-control" value="">
                    </div>
                    <div class="form-group">
                        <label for="gl_D">D. 没受灾没赔偿</label>
                        <input id="gl_D" type="number" class="form-control" value="">
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            <button id="submit" class="btn btn-success">修改</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('#submit').click(function(){
            var gl_a = $('#gl_A')[0].value;
            var gl_b = $('#gl_B')[0].value;
            var gl_c = $('#gl_C')[0].value;
            var gl_d = $('#gl_D')[0].value;
            if (gl_a < 0 || gl_a > 100000
                || gl_b < 0 || gl_b > 100000
                || gl_c < 0 || gl_c > 100000
                || gl_d < 0 || gl_d > 100000){
                alert("无效值");
                return;
            }
        })
    </script>
</body>
</html>